language: python
cache: pip
matrix:
  include:
    - python: '3.5'
      env:
        - TOXENV=py35,report,codecov
    - python: '3.6'
      env:
        - TOXENV=py36,report,codecov
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgirepository1.0-dev
install:
  - pip install tox
script:
  - tox -v
