language: python
cache: pip
matrix:
  include:
    - python: '3.5'
      env:
        - TOXENV=py35,report,codecov
    - python: '3.6'
      env:
        - TOXENV=py36,report,codecov
install:
  - pip install tox
script:
  - tox -v
